name: hw1_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - pip
  - pip:
      - transformers
      - datasets
      - evaluate
      - tqdm
      - diffusers
      - huggingface-hub
      - pillow
      - pandas